### ISSUE TITLE
undefined method `close' for nil:NilClass

### ISSUE THREAD

**Issue by terminalninja** [chef-cookbooks/database#173] opened 2015-09-14 06:29 UTC
Hi I get the following error on executing my code
code

---

mysql_database 'flush the privileges' do
&nbsp;  connection mysql_connection_info
&nbsp;  sql        'flush privileges'
&nbsp;  action     :query
end

---

following is the error I get when I provision my vagrant machine

---

 ERROR: Running exception handlers
[2015-09-14T06:17:33+00:00] ERROR: Exception handlers complete
[2015-09-14T06:17:33+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-09-14T06:17:33+00:00] ERROR: mysql_database[flush the privileges](vagrant_stage::default line 176) had an error: NoMethodError: undefined method `close' for nil:NilClass
# 
# Error executing action `query` on resource 'mysql_database[flush the privileges]'
## NoMethodError

undefined method `close' for nil:NilClass
## Cookbook Trace:

/tmp/vagrant-chef-1/chef-solo-1/cookbooks/database/libraries/provider_database_mysql.rb:153:in `close_query_client'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/database/libraries/provider_database_mysql.rb:96:in`ensure in block in class:Mysql'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/database/libraries/provider_database_mysql.rb:96:in `block in class:Mysql'

Any help is appreciated.

**Comment by tas50** [comment] 2015-09-14 07:20
This is probably related to this change: https://github.com/chef-cookbooks/database/commit/284faca563f54d50405a9594a6b5f63695a4fbb7

I'm going to see what I can do to solve both issues.

**Comment by appusidhardh** [comment] 2015-09-14 07:26
@tas50 Thank you. I am able to create database, mysql user this happens only when I try to execute a query.

**Comment by thorstenk** [comment] 2015-09-17 16:40
@tas50 Same issue here. Commenting out the line added with 284faca (`database: new_resource.database_name`) helps here.

**Comment by thorstenk** [comment] 2015-09-18 08:02
I guess I've found the cause of the issue: `Chef::Resource::Database#initialize` initializes the `@database_name` with the name of the resource. So when utilizing the resource and there's no explicit `@database_name` set (or the resource name accidentally matches an existing table name) you get an "Unknown database" MySQL error.

284faca introduces a breaking change: the `database_name` has to be set for every database and database_user resource now. I suggest to revert that commit.

**Comment by appusidhardh** [comment] 2015-09-18 12:01
Its working fine if you remove the last commit. Thanks @thorstenk

**Comment by jslusher** [comment] 2015-10-22 18:52
I'm getting this exception when trying to run a query on a database. I verified that the user info and the query works manually. Should it be working now or is this still an issue?

    Error executing action `query` on resource 'mysql_database[grant datadog user replication client]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `close' for nil:NilClass

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/wrapper-mysql/recipes/create_database.rb

            38:   mysql_database 'grant datadog user replication client' do
            39:     connection mysql_connection_info
            40:     sql "grant replication client on *.* to 'datadog'@'localhost' with max_user_connections 5"
            41:     action :query
            42:   end
            43: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/wrapper-mysql/recipes/create_database.rb:38:in `from_file'

           mysql_database("grant datadog user replication client") do
             provider Chef::Provider::Database::Mysql
             action [:query]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             database_name "grant datadog user replication client"
             declared_type :mysql_database
             cookbook_name "wrapper-mysql"
             recipe_name "create_database"
             connection {:host=>"127.0.0.1", :username=>"root", :password=>"password"}
             sql "grant replication client on *.* to 'datadog'@'localhost' with max_user_connections 5"
           end

**Comment by appusidhardh** [comment] 2015-10-23 07:08
Have you tried roll backing this commit https://github.com/chef-cookbooks/database/commit/284faca563f54d50405a9594a6b5f63695a4fbb7 ?

**Comment by jslusher** [comment] 2015-10-23 20:24
I assume that would work, but I feel like if the latest version is broken, there should be a later version that is not broken. I'm not doing much with this lwrp at the moment, so it's not worth the trouble to make the exception. Is this going to get fixed in the default version anytime soon?

**Comment by pniederlag** [comment] 2015-11-08 14:23
+1 user that is affected by this bug.

**Comment by eric-tucker** [comment] 2016-04-08 11:21
This is still an issue using 4.0.9.

**Comment by jpujari-cartera** [comment] 2016-11-29 16:08
This is still an issue using 4.0.9

**Comment by tas50** [comment] 2017-02-22 19:27
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.

**Closed by tas50** 2017-02-22 19:27 UTC
