### ISSUE TITLE
Error executing action create on resource 'mysql_database[aws]' 

### ISSUE THREAD

**Issue by zanjibar** [chef-cookbooks/database#133] opened 2015-02-15 12:43 UTC
tag v4.0.2 
removing mysql recipe that installs mysql2_chef_gem

might cause this error ?

I add my-database cookbook    

in metadata.rb
depentd "mysql2_chef_gem"

and
in recipe

mysql2_chef_gem 'default' do
  client_version node['mysql']['version'] if node['mysql']
  action :install
end

this workaround work fine for me. 

but this problem might resolve if metadata.rb has "depends ''mysql2_chef_gem"
and mysql.rb remain ( not removed )

**Comment by ajkerr** [comment] 2015-02-17 20:21
I had the same issue after upgrading to 4.0.2.  Reverting to 4.0.1 fixed the issue for me.  My cookbook has dependencies on database, mysql and mysql2_chef_gem.

To use 4.0.2 of the database cookbook, I had to remove the include_recipe "database::mysql" line from my recipe.  However, this prevents the mysql2 gem from ever being installed, unless you do it yourself.

**Comment by danhanly** [comment] 2015-04-20 08:02
I had this exact issue when I used certain special characters in my mysql password.
I changed it to alpha-numeric characters and it seemed to work fine from then-on.

[This database thread](http://dba.stackexchange.com/questions/48778/mysqladmin-not-taking-inline-password) alludes to the cause of this issue, along with a list of potential issue-causing special characters. 

```
$ & ! \ [ ] < > `
```

I added this information here, because I found this thread whilst trying to debug the error I was receiving and I thought this may be of interest to any potential future visitors.

**Comment by tas50** [comment] 2017-02-22 19:26
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.

**Closed by tas50** 2017-02-22 19:26 UTC
Labels: Type: Bug
