### ISSUE TITLE
Error occurred 'cannot load such file -- mysql2'

### ISSUE THREAD

**Issue by Genzou** [chef-cookbooks/database#148] opened 2015-04-11 15:44 UTC
Please Teach me how to fix this error 'cannot load such file -- mysql2'
My target server is AWS EC2(Amazon Linux).
## [my recipe]

mysql_connection_info = {
  :host     => '127.0.0.1',
  :username => 'root',
  :password => 'password!'
}
mysql_database 'aws' do
  connection mysql_connection_info
  action :create
## [error] 

 \ \* mysql_database[aws] action create
 ================================================
#     Error executing action `create` on resource 'mysql_database[aws]'  

```
LoadError
---------
cannot load such file -- mysql2
Cookbook Trace:
---------------
/home/ec2-user/chef-solo/cookbooks-2/database/libraries/provider_database_mysql.rb:103:in `test_client'
/home/ec2-user/chef-solo/cookbooks-2/database/libraries/provider_database_mysql.rb:37:in `block in <class:Mysql>'
```

---

I thought that EC2 has not mysql2 of gem.
But EC2 has mysql2 of  gem
$ gem list
**\* LOCAL GEMS ***
bigdecimal (1.2.0)
json (1.7.7)
mysql2 (0.3.18)
psych (2.0.0)
rdoc (4.0.1)

and I confirmed this code works fine.
$ ruby hello.rb
Hello World
## [hello.rb] is 

 require "rubygems"
 require "mysql2" # I want to confirm this line
##  puts 'Hello World'

Someone tell me how to solve this error...

**Comment by someara** [comment] 2015-04-11 21:15
You'll need to use the mysql2_chef_gem resource from the mysql2_chef_gem
cookbook.

**Comment by Genzou** [comment] 2015-04-12 01:59
Thank you very much  for your message.

I guess my recipe uses  mysql2_chef_gem.
[Part of Log]
$  bundle exec knife solo cook aws(node_name)
------------------------------------------------------
Using mysql2_chef_gem (1.0.1)
Vendoring mysql2_chef_gem (1.0.1) to cookbooks/mysql2_chef_gem
------------------------------------------------------

And I show some other codes.
[Berksfile]
cookbook "yum" 
cookbook "mysql2_chef_gem" 
cookbook "database" 

[metadata.rb]
------------------------------------------------
depends 'mysql2_chef_gem', '~> 1.0.1'  
depends 'database', '~> 4.0.6'  
------------------------------------------------

**Comment by someara** [comment] 2015-04-12 02:08
protip: use the integration test cookbooks for examples =)

https://github.com/opscode-cookbooks/database/blob/master/test/fixtures/cookbooks/mysql_database_test/recipes/default.rb#L8

-s

**Comment by Genzou** [comment] 2015-04-12 03:07
Thank you for your suggestion again.
I tried to do test code.
But I have some errors ...

[metadata.rb]
depends 'mysql2_chef_gem', '~> 1.0.1'
depends 'database', '~> 4.0.6'
depends 'mysql'

[myrecipe]
mysql_service 'default' do
  version node['mysql']['version'] if node['mysql'] && node['mysql']['version']
  port '3306'
  initial_root_password 'password!'
  action [:create, :start]
end

[attributes/default.rb]
default['mysql']['version']='5.5'

[Errors]

   Error executing action `create` on resource 'mysql_service[default]'
    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass

    Cookbook Trace:
    ---------------
    /home/ec2-user/chef-solo/cookbooks-2/mysql/libraries/helpers.rb:338:in `package_name_for'
    /home/ec2-user/chef-solo/cookbooks-2/mysql/libraries/helpers.rb:379:in `server_package'
    /home/ec2-user/chef-solo/cookbooks-2/mysql/libraries/helpers.rb:390:in `server_package_name'
    /home/ec2-user/chef-solo/cookbooks-2/mysql/libraries/provider_mysql_service.rb:32:in `block in <class:MysqlService>'

    Resource Declaration:
    ---------------------
    # In /home/ec2-user/chef-solo/cookbooks-3/sample/recipes/default.rb

     20: mysql_service 'default' do
     21:   version node['mysql']['version'] if node['mysql'] && node['mysql']['version']
     22:   port '3306'
     23:   initial_root_password ''
     24:   action [:create, :start]
     25: end
     26:

    Compiled Resource:
    ------------------
    # Declared in /home/ec2-user/chef-solo/cookbooks-3/sample/recipes/default.rb:20:in `from_file'

    mysql_service("default") do
      action [:create, :start]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :mysql_service
      cookbook_name :sample
      recipe_name "default"
      version "5.5"
      port "3306"
    end

**Comment by webbower** [comment] 2015-05-19 19:47
Careful with setting the `initial_root_password` to empty string. I don't think that's what is causing your problem but it will make it so any database you create and try to access going forward will fail. I logged a ticket about it https://github.com/chef-cookbooks/mysql/issues/340

**Comment by Genzou** [comment] 2015-05-20 15:27
Thank you for your comment.
I'm glad to mention this issue.

I tried to set 'not empty password'.
( initial_root_password 'some strings'）
But I got same error.

**Error**
Error executing action create on resource 'mysql_service[default]'
NoMethodError
-------------
undefined method `[]' for nil:NilClass

**Comment by barryku** [comment] 2015-12-20 02:14
Got the same error, and resolved by adding the following code in my recipe per suggestions at http://lists.opscode.com/sympa/arc/chef/2015-02/msg00244.html,

mysql2_chef_gem 'default' do
  action :install
end

**Comment by digilist** [comment] 2016-07-07 11:42
@barryku is right, you need to put a mysql2_chef_gem resource before you use the database resource.

See #141. This is a duplicate of that one

**Comment by venugopalanAG** [comment] 2016-09-01 09:01
It got solved after installing chef gem

`**gem install chef --no-ri --no-rdoc**`

**Comment by cheeseplus** [comment] 2017-02-21 19:42
Closing as answered and dupe of #141

**Closed by cheeseplus** 2017-02-21 19:42 UTC
